services:
- type: web
  name: line-news-bot
  env: python
  repo: https://github.com/Zeng-GL/python-news-crawler.git
  buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
  startCommand: cd examples/flask-echo;gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: Channel access token
  - key: Channel Secret
    sync: false